### ISSUE TITLE
error_description: The client type is invalid.

### ISSUE THREAD

**Issue by cuongpv0504** [chatwork/oauth2-chatwork-php#2]
I'm try to using oauth2-chatwork-php for my app to get accessToken. It success generate Authorization Url but after i click on that url it return "error: invalid_client, error_description: The client type is invalid., error_uri:" instead of accessToken.

Here is my code:

    public function oauth()
	{
		$this->autoRender = false;
		$provider = new ChatWorkProvider(
		    OAUTH2_CLIENT_ID,
		    OAUTH2_CLIENT_SECRET,
		    OAUTH2_REDIRECT_URI
		);
		$url = $provider->getAuthorizationUrl([
		    'scope' => ['users.all:read', 'rooms.all:read_write']
		]);

		echo "<a href='$url'>Login with chatwork</a>";
	}

	public function callback()
	{
		$this->autoRender = false;

		$provider = new ChatWorkProvider(
		    OAUTH2_CLIENT_ID,
		    OAUTH2_CLIENT_SECRET,
		    OAUTH2_REDIRECT_URI
		);

		$accessToken = $provider->getAccessToken((string) new AuthorizationCode(), [
		    'code' => $_GET['code']
		]);
		pr($accessToken->getToken());
	}

Can you help me with this?

**Comment by arai-ta** [comment]
@cuongpv0504 
Hi,
I'm encountered the same problem.
I fixed it and v0.1.2 was released.
https://github.com/chatwork/oauth2-chatwork-php/releases/tag/v0.1.2
Could you try this version?
